language: node_js
node_js: "8"
addons:
  apt:
    packages:
      - mysql-server-5.7
      - mysql-client-core-5.7
      - mysql-client-5.7
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
